import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, unlinkSync, rmdirSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
import React, { act } from 'react';
import { initialGame } from '../src/data/scenario.js';
import { loadProgress, saveProgress } from '../src/data/progress.js';

test('React screens connect resume, profiles, stories, search, review and restart', async () => {
  const folder = mkdtempSync(join(process.cwd(), 'node_modules', '.decon-ui-'));
  const output = join(folder, 'app.mjs');
  const dom = new JSDOM('<div id="root"></div>', { url: 'http://localhost/jcj-team/' });
  const globals = ['window', 'document', 'navigator', 'HTMLElement', 'localStorage', 'IS_REACT_ACT_ENVIRONMENT'];
  const originals = new Map(globals.map(key => [key, Object.getOwnPropertyDescriptor(globalThis, key)]));
  for (const key of globals) Object.defineProperty(globalThis, key, { configurable: true, writable: true, value: key === 'IS_REACT_ACT_ENVIRONMENT' ? true : dom.window[key] });
  dom.window.HTMLElement.prototype.scrollIntoView = function () {};
  dom.window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  dom.window.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); };
  let root;
  const click = async element => { assert.ok(element, 'click target exists'); await act(async () => element.click()); };
  const button = (label, scope = document) => [...scope.querySelectorAll('button')].find(item => item.textContent.trim() === label);
  const fill = async (element, value) => {
    assert.ok(element);
    const prototype = element.tagName === 'TEXTAREA' ? dom.window.HTMLTextAreaElement.prototype : dom.window.HTMLInputElement.prototype;
    await act(async () => { Object.getOwnPropertyDescriptor(prototype, 'value').set.call(element, value); element.dispatchEvent(new dom.window.Event('input', { bubbles: true })); });
  };
  try {
    await build({ entryPoints: ['src/App.jsx'], outfile: output, bundle: true, platform: 'node', format: 'esm', packages: 'external', loader: { '.css': 'empty' }, logLevel: 'silent' });
    const { default: App } = await import(pathToFileURL(output).href);
    const { createRoot } = await import('react-dom/client');
    const game = { ...initialGame('지민'), started: true, phase: 'awaitingReply', companyReceived: true, messages: [{ sender: 'boss', text: '회사 자료를 확인하고 시안을 준비해 주세요.', time: '09:00', week: 1, attachment: 'company' }] };
    saveProgress({ game, socials: {}, socialTime: 0, seenStories: [], reply: '기대됩니다. 작성 중인 답장' }, localStorage);
    root = createRoot(document.getElementById('root'));
    await act(async () => root.render(React.createElement(App)));
    assert.ok(button('이어서 하기'));
    assert.equal(loadProgress(localStorage).snapshot.game.phase, 'awaitingReply', 'landing screen does not overwrite save');
    await click(button('이어서 하기'));
    assert.equal(document.querySelectorAll('.story-button').length, 1);
    assert.equal(document.querySelectorAll('.world-post').length, 3);
    assert.equal(document.querySelector('.brand').textContent, '페이크그램');
    assert.equal(document.querySelector('.account-shortcuts'), null);
    assert.equal(document.querySelector('main .heading'), null);
    assert.equal(document.querySelector('.social-reactions'), null);
    const firstPost = document.querySelector('.world-post');
    await click(firstPost.querySelector('[aria-label="댓글 보기"]'));
    assert.ok(firstPost.querySelector('.comment-empty'));
    assert.equal(button('게시', firstPost).disabled, true);
    await fill(firstPost.querySelector('[aria-label="댓글 내용"]'), '새로운 댓글입니다');
    await click(button('게시', firstPost));
    assert.ok(firstPost.querySelector('.social-comments').textContent.includes('새로운 댓글입니다'));
    const savedComments = Object.values(loadProgress(localStorage).snapshot.socials).flatMap(value => value.comments || []);
    assert.ok(savedComments.includes('새로운 댓글입니다'));
    await click(firstPost.querySelector('[aria-label="댓글 보기"]'));
    assert.equal(firstPost.querySelector('.comment-panel'), null);
    await click(firstPost.querySelector('[aria-label="댓글 보기"]'));
    assert.ok(firstPost.querySelector('.social-comments').textContent.includes('새로운 댓글입니다'));
    await click(button('둘러보기'));
    assert.equal(document.querySelectorAll('.reference-card').length, 10);
    await click(document.querySelector('.reference-card [aria-label="댓글 보기"]'));
    await fill(document.querySelector('.reference-card [aria-label="댓글 내용"]'), '참고할게요');
    await click(button('게시', document.querySelector('.reference-card')));
    assert.ok(document.querySelector('.reference-card .social-comments').textContent.includes('참고할게요'));
    await click(button('홈'));
    await click(document.querySelector('.story-button'));
    assert.ok(document.querySelector('dialog[open] .story-canvas'));
    assert.deepEqual(loadProgress(localStorage).snapshot.seenStories, ['story-1']);
    await click(document.querySelector('.world-close'));
    await click(document.querySelectorAll('.suggested-account')[0]);
    assert.ok(document.querySelector('dialog').textContent.includes('디컨'));
    await click(button('대표 윤하은 프로필 →'));
    assert.ok(document.querySelector('dialog').textContent.includes('yoonhaeun.ceo'));
    await click(button('대표님과의 업무 대화'));
    assert.equal(document.querySelector('textarea').value, '기대됩니다. 작성 중인 답장');
    await fill(document.querySelector('[aria-label="대화 기록 검색"]'), '없는말');
    assert.ok(document.querySelector('.message-empty'));
    await fill(document.querySelector('[aria-label="대화 기록 검색"]'), '회사소개');
    assert.equal(document.querySelectorAll('.chat').length, 1);
    await click(button('검색 지우기 · 전체 대화'));
    await click(button('범위 확인하기'));
    assert.ok(document.querySelector('textarea').value.includes('범위'));
    assert.equal(loadProgress(localStorage).snapshot.game.replyCount, 0, 'choosing a draft does not send it');
    assert.ok(loadProgress(localStorage).snapshot.reply.includes('범위'));
    await click(button('주차별 회고 ↗'));
    assert.ok(document.querySelector('dialog').textContent.includes('내가 남긴 기록'));
    assert.equal(document.querySelectorAll('.review-week-tabs button:disabled').length, 6);
    await click(button('전체 대화 보기 →'));
    assert.equal(document.querySelector('[aria-label="대화 주차 필터"]'), null);
    assert.equal(document.querySelector('[aria-label="대화 기록 검색"]').value, '');
    await act(async () => root.unmount());
    root = createRoot(document.getElementById('root'));
    await act(async () => root.render(React.createElement(App)));
    await click(button('공고부터 새로 시작'));
    await click(button('취소'));
    assert.ok(loadProgress(localStorage).snapshot, 'cancel keeps the save');
    await click(button('공고부터 새로 시작'));
    await click(button('새 게임 시작'));
    assert.equal(loadProgress(localStorage).snapshot, null);
    assert.ok(document.getElementById('player-name'));
    await fill(document.getElementById('player-name'), '새 이름');
    await click(button('지원하기'));
    assert.equal(loadProgress(localStorage).snapshot.game.name, '새 이름');
    assert.deepEqual(loadProgress(localStorage).snapshot.seenStories, []);
    await act(async () => root.unmount());
    saveProgress({ game: { ...game, phase: 'drafting' }, socials: {}, socialTime: 0, seenStories: [], reply: '' }, localStorage);
    root = createRoot(document.getElementById('root'));
    await act(async () => root.render(React.createElement(App)));
    await click(button('이어서 하기'));
    await click(button('만들기'));
    assert.ok(document.querySelector('.composer-modal'));
    assert.equal(document.querySelectorAll('.composer-preview .design').length, 1);
    assert.equal(document.querySelectorAll('.swatches button').length, 16);
    await click(document.querySelector('.swatches [aria-label="#67518c"]'));
    assert.equal(loadProgress(localStorage).snapshot.game.draft.color, '#67518c');
    await fill(document.querySelector('[aria-label="사용자 지정 배경색"]'), '#123456');
    assert.equal(loadProgress(localStorage).snapshot.game.draft.color, '#123456');
  } finally {
    if (root) await act(async () => root.unmount());
    dom.window.close();
    for (const [key, descriptor] of originals) { if (descriptor) Object.defineProperty(globalThis, key, descriptor); else delete globalThis[key]; }
    try { unlinkSync(output); } catch {}
    rmdirSync(folder);
  }
});
